### PR TITLE
Issue #67: Fix double function declaration

### LINKED ISSUE #67: Cannot redeclare metatag_views_views_plugins() (previously declared in ../modules/metatag/metatag_views/metatag_views.module:21) in ...modules/metatag/metatag_views/metatag_views.views.inc on line 21
When trying to install  Metatag Views module I get this error:
Cannot redeclare metatag_views_views_plugins() (previously declared in ../modules/metatag/metatag_views/metatag_views.module:21) in ...modules/metatag/metatag_views/metatag_views.views.inc on line 21
The function is in both files.

### PR DESCRIPTION
**Pull request by indigoxela**
Fixes #67

### CODE REVIEW

**Comment by yorkshire-pudding** [comment]
I've tested on the local that had the issue and re-enabled metatag_views and it's fine.  I've also tested the update on another site with metatag and it works there too.

**Comment by Egarbeil** [comment]
I ran into this on one of my sites in development as well updating to the latest release (1.22.2) .  The fix works and the site is now back up.  I just commented out the function for now.  Most likely will have to do so on all backdrop sites until this makes it into the next release.

**Comment by quicksketch** [comment]
A couple things needed here:

* If Views prior to Backdrop 1.22.1 was not including `metatag.views.inc` we should add `path` to `metatag_views_api()` so that the .inc file gets pulled in for those older versions.
* The `metatag.views.inc` instance of `metatag_views_views_plugins()` had a `drupal_get_path()` in it.

**Comment by quicksketch** [comment]
I made a follow-up commit at https://github.com/backdrop-contrib/metatag/commit/3f0f9928c42256839dde2f206b1c384e51e6a902 that fixes the above two points.

**Pull request merged**
